### PR TITLE
New icns file courtesy of https://dribbble.com/shots/1663619-LICEcap-R…

### PR DESCRIPTION
**Pull request by aluncoppack**
…eplacement-Icon @cjdowner

### CODE REVIEW

**Comment by dialex** [comment]
Please, someone merge this already!! :sob:
The old icon looks terrible (specially on macs), and the logo suggested is basically the same (so no branding problems there) but done beautifully. Props to the designer :+1:

**Comment by dialex** [comment]
please @justinfrankel have a look at it

**Comment by cjdowner** [comment]
Would be really nice to see the icon in the project. I would be more than happy to work with you to create something different, or make tweaks to the original if you so wished.

**Comment by un1versal** [comment]
The original icon is like Freddy Kruger and Ripleys Alien had a mutant baby. and this one while an improvement is only for OSX + the 16x16 could do with a little more thought.
I agree with @cjdowner should get 1 to 1 attention.

**Comment by wenbinke** [comment]
The old icon is super ugly on mac, I strongly suggest to use the new icon. @justinfrankel

**Comment by un1versal** [comment]
@cjdowner I can work with you to design an Icon for both platforms, ping me on freenode IRC.

**Comment by qaisjp** [comment]
Slightly bumping this project, hey @justinfrankel!

**Comment by dialex** [comment]
Please @justinfrankel, PLEASE click the "Merge" button.
puss-in-boots

**Comment by dialex** [comment]
@justinfrankel please please please!

**Comment by kbilsted** [comment]
Perhaps @dialex  you should fork the project and merge all the PRs?

**Comment by dialex** [comment]
That's a great idea, I didn't know I could do that.. POWER TO THE PEOPLE! 😁 
New fork at: https://github.com/dialex/licecap

**Comment by kbilsted** [comment]
@dialex  Perhaps give it a new name something like "licecap 365" ;)

**Comment by dialex** [comment]
Done @kbilsted

**Comment by esaruoho** [comment]
.icns looks pretty nice, running it on 1.27 now locally on macOS High Sierra.
Cool!

**Comment by dialex** [comment]
@justinfrankel did you merge this?

**Comment by justinfrankel** [comment]
Not merging this, but improved the existing icons to be less cruddy.

**Pull request closed without merging**
