### PR TITLE
64-bit Version

### PR DESCRIPTION
**Pull request by ppaulojr**
Adding project support to 64-bit in order to be compatible with newer MacOS versions.

### CODE REVIEW

**Comment by asimonov** [comment]
worked for me on High Sierra!

**Comment by regnarock** [comment]
Very much needed!

**Comment by ppaulojr** [comment]
Is this project still alive? Maybe we can fork it and release a new build. Not sure about the licensing though.

**Comment by getaaron** [comment]
@ppaulojr From https://www.cockos.com/licecap/:

> LICEcap is GPL free software

See https://en.wikipedia.org/wiki/GNU_General_Public_License

**Comment by ppaulojr** [comment]
I just wanted to see if @justinfrankel give us the green light.

**Comment by sammcj** [comment]
Any update on this @justinfrankel, was just about to clone it and do the same thing?

**Comment by justinfrankel** [comment]
You're free to clone it obviously, but I'll put together a new release soon.

**Comment by esaruoho** [comment]
thanks @justinfrankel , much appreciated! then all three tickets referencing this ( #40  #46  #49 ) can be closed :)

**Comment by esaruoho** [comment]
@justinfrankel any chance this PR could get merged in?

**Comment by esaruoho** [comment]
oh no, `licecap/licecap.xcodeproj/project.pbxproj` conflicting file :o

**Comment by justinfrankel** [comment]
Probably should use ours ;)

**Comment by esaruoho** [comment]
@justinfrankel harsh but fair! so i guess it's easier for you to make a 64-bit compile of licecap than to use this PR that you just closed?

**Comment by sammcj** [comment]
Is there a 64bit build available now? 1.28 is still 32bit right?

**Comment by justinfrankel** [comment]
I've made a test macOS build of 1.29, available here for now: https://landoleet.org/licecap129.dmg -- let me know if this version has any issues (I'll post it to cockos.com later this week if no issues arise).

**Comment by sammcj** [comment]
Legend! Thank you @justinfrankel :)

**Comment by sammcj** [comment]
No issues thus far, file sizes might be a little larger but not a big deal:

licecap_x64_test

(5.5MB)

**Comment by esaruoho** [comment]
> I've made a test macOS build of 1.29, available here for now: https://landoleet.org/licecap129.dmg -- let me know if this version has any issues (I'll post it to cockos.com later this week if no issues arise).

thank you VERY much, @justinfrankel  - i've been dying for this to appear :)

**Pull request closed without merging**
